### ISSUE TITLE
Segmentations Faults 

### ISSUE THREAD

**Issue by francesca-figueroa** [rnarkus/Hudobnik_CSCI2270_FinalProject#3]
Hi. I was looking through your code, and I just wanted to say that I think your idea is very cool! It was easy to install and run. There were minim errors when initially compiling, with the exception of one missing semicolon at the end of line 64 in your "FinalProject.cpp". I noticed in the Delete Response option, the item being deleted was one index off. For example, if I typed delete response 1, it would delete response at index 0. Or if I deleted response 0, the program would throw a segmentation fault. I fixed that in the code I submitted to you. Also, when I am in the program, not in the options menu, and I am "talking" with Bob, if I enter a phrase that would fall under the "unknown" keyword category, the program doesn't generate a response. I'm not sure exactly why that is, but I am pretty sure that in your searchStr function that the foundResp variable is always being set to a value, that is not NULL, regardless of if the keyword is found or not. Overall though, your code was brilliantly executed, and very interesting. You explained your functions very well. Very well done.

**Comment by rnarkus** [comment]
Thanks for the feedback!
